### PR TITLE
xtensa: add build support for mt8186

### PR DESCRIPTION
**Pull request by tinghan-shen**
Add gcc build support for gcc10.x and gdb9.x on mt8186 platform.

Signed-off-by: Allen-KH Cheng <allen-kh.cheng@mediatek.com>
Signed-off-by: Tinghan Shen <tinghan.shen@mediatek.com>

### CODE REVIEW

**Review by dbaluta — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@tinghan-shen thanks, can you do teh same for GCC11 as we will transition to GCC11 soon.
@marc-hb @greg-intel any reason why CI here is building for targets we dont use ?

**Comment by greg-intel** [comment]
@lgirdwood in the GitHub checks?  It's just a list of targets, doesn't look like it has any filtering logic.  
Is this what you're referring to?
https://github.com/thesofproject/crosstool-ng/actions/runs/1743337163/workflow#L62
It can be edited here:
https://github.com/thesofproject/crosstool-ng/edit/sof-gcc10x/.github/workflows/continuous-integration-workflow.yml

I apologize if this isn't what you were talking about, let me know how I can assist.

**Comment by marc-hb** [comment]
> @marc-hb @greg-intel any reason why CI here is building for targets we dont use ?

The `.github/workflows/` are not ours, they're from upstream crosstool-ng.
https://github.com/thesofproject/crosstool-ng/commits/sof-gcc10x/.github/workflows
I'd like to keep as many of them as possible to 1) minimize divergence and git conflicts, and 2) find as many issues as possible.

This being said, these frequent and semi-random macos segfaults seem unrelated and they are distracting. @greg-intel could you find a way to turn off just macos with a minimal amount of `.github/workflows/` changes?

@galak I see you added macos in commit 752cc393783609ff1762. Have you ever seen these segfaults before?

Example https://github.com/thesofproject/crosstool-ng/runs/4931460389
```
[EXTRA]    Building m4
/Users/runner/work/crosstool-ng/crosstool-ng/.local/share/crosstool-ng/scripts/functions: line 391: 26011 Segmentation fault: 11  "${@}" 2>&1
     26012 Done                    | CT_DoLog "${level}"
Error:   
Error:   >>
Error:   >>  Build failed in step 'Installing m4 for build'
Error:   >>        called in step '(top-level)'
Error:   >>
Error:   >>  Error happened in: CT_DoExecLog[scripts/functions@376]
Error:   >>        called from: do_m4_backend[scripts/build/companion_tools/100-m4.sh@77]
Error:   >>        called from: do_companion_tools_m4_for_build[scripts/build/companion_tools/100-m4.sh@18]
Error:   >>        called from: do_companion_tools_for_build[scripts/build/companion_tools.sh@35]
Error:   >>        called from: main[scripts/crosstool-NG.sh@695]
Error:   >>
Error:   >>  For more info on this error, look at the file: 'build.log'
Error:   >>  There is a list of known issues, some with workarounds, in:
Error:   >>      https://crosstool-ng.github.io/docs/known-issues/
```

**Comment by greg-intel** [comment]
@marc-hb I believe it's as easy as changing this:
```
        host: [
          "ubuntu-latest",
          "macos-10.15",
        ]
```
to this (updated):
```
host: [
  "ubuntu-latest",
]
```

Will have a PR in shortly.
EDIT
- #14

**Pull request merged**
