### PR TITLE
xtensa: add build support for imx8ulp

### PR DESCRIPTION
**Pull request by dbaluta**
Add gcc build support for gcc10.x and gdb9.x on i.MX8ULP platform.

Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>

### CODE REVIEW

**Comment by dbaluta** [comment]
@lgirdwood please do not merge this yet. 

@potochi please test this.

**Comment by dbaluta** [comment]
OK, All good. This is ready to merge.

**Review by lgirdwood — APPROVED** [review]
@dbaluta I assume you will take care of uploading a binary to the GCC releases in SOF GH.

**Comment by dbaluta** [comment]
@lgirdwood this is our next step. Can you quickly remind me where should I upload the binaries for imx8ulp. Otherwise, I will try to look through emails.

Cc: @Potochi, can you also send the docker changes PR?

**Comment by lgirdwood** [comment]
> @lgirdwood this is our next step. Can you quickly remind me where should I upload the binaries for imx8ulp. Otherwise, I will try to look through emails.

https://github.com/thesofproject/crosstool-ng/releases/tag/gcc10.2

**Comment by dbaluta** [comment]
@lgirdwood it looks like i'm not able to create a new release. Can you help us with this:

The archive with the toolchain for imx8ulp is here: https://we.tl/t-FpGDih7A3X

Or grant me some more access rights and I'll do it :)

**Comment by lgirdwood** [comment]
@dbaluta give it a try now.

**Comment by dbaluta** [comment]
@lgirdwood thanks it works. 

Updated release with imx8ulp gcc toolchain:
 https://github.com/thesofproject/crosstool-ng/releases/tag/gcc10.2

**Pull request merged**
